"""Platform health models — immutable dataclasses for dashboard aggregation."""

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional


class HealthStatus(str, Enum):
    """Overall health indicator for a component or the platform."""

    HEALTHY = "healthy"
    DEGRADED = "degraded"
    UNHEALTHY = "unhealthy"
    UNKNOWN = "unknown"


class ComponentType(str, Enum):
    """Classification of platform subsystem components."""

    QUEUE = "queue"
    WORKER = "worker"
    LOCK = "lock"
    EVENT = "event"
    NOTIFICATION = "notification"
    METRICS = "metrics"
    AUDIT = "audit"
    SSE = "sse"


class AlertSeverity(str, Enum):
    """Severity level for operational alerts."""

    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


@dataclass(frozen=True)
class SystemComponentHealth:
    """Health status of a single platform subsystem.

    Attributes:
        component: The subsystem type.
        name: Human-readable name for display.
        status: Current health status.
        message: Descriptive health message.
        metrics: Key-value pairs of component-specific metrics.
        last_checked: UTC timestamp of last health check.
    """

    component: ComponentType
    name: str
    status: HealthStatus
    message: str
    metrics: Dict[str, Any] = field(default_factory=dict)
    last_checked: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


@dataclass(frozen=True)
class OperationalAlert:
    """An alert generated by the alert evaluation engine.

    Attributes:
        rule_id: Unique identifier for the alert rule.
        severity: Alert severity level.
        component: Which subsystem triggered the alert.
        title: Short alert title.
        message: Detailed alert message.
        recommended_action: Suggested operator action.
        metrics: Key-value pairs of triggering metric values.
        timestamp: UTC timestamp when the alert was generated.
    """

    rule_id: str
    severity: AlertSeverity
    component: ComponentType
    title: str
    message: str
    recommended_action: str
    metrics: Dict[str, Any] = field(default_factory=dict)
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


@dataclass(frozen=True)
class AlertRule:
    """Definition of an alert evaluation rule.

    Attributes:
        rule_id: Unique rule identifier.
        severity: Alert severity when rule fires.
        component: Which subsystem this rule monitors.
        title: Short alert title template.
        message_template: Format string for alert message (uses .format(**metrics)).
        recommended_action: Suggested operator action.
        warning_threshold: Threshold value that triggers a WARNING.
        critical_threshold: Threshold value that triggers a CRITICAL.
        metric_name: Name of the metric to evaluate.
        comparator: Comparison operator ('gt', 'lt', 'eq', 'gte', 'lte').
    """

    rule_id: str
    severity: AlertSeverity
    component: ComponentType
    title: str
    message_template: str
    recommended_action: str
    warning_threshold: float
    critical_threshold: float
    metric_name: str
    comparator: str = "gt"


@dataclass(frozen=True)
class DashboardSnapshot:
    """Complete snapshot of platform health for the operations dashboard.

    Attributes:
        overall_status: Aggregate health status across all components.
        components: Health status of each subsystem.
        alerts: Active alerts generated during this snapshot.
        timestamp: UTC timestamp of snapshot creation.
        kpi_summary: Key performance indicators from the metrics platform.
        queue_metrics: Queue engine metrics (pending, running, failed, etc.).
        worker_metrics: Worker daemon metrics (active workers, heartbeats).
        lock_metrics: Lock manager metrics (active, expired, contention).
        event_metrics: Event store metrics (events per category, total).
        notification_metrics: Notification metrics (unread, by category).
        audit_metrics: Audit trail metrics (total records, incidents).
        sse_metrics: SSE streaming metrics (active clients, events delivered).
    """

    overall_status: HealthStatus
    components: List[SystemComponentHealth] = field(default_factory=list)
    alerts: List[OperationalAlert] = field(default_factory=list)
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    kpi_summary: Dict[str, Any] = field(default_factory=dict)
    queue_metrics: Dict[str, Any] = field(default_factory=dict)
    worker_metrics: Dict[str, Any] = field(default_factory=dict)
    lock_metrics: Dict[str, Any] = field(default_factory=dict)
    event_metrics: Dict[str, Any] = field(default_factory=dict)
    notification_metrics: Dict[str, Any] = field(default_factory=dict)
    audit_metrics: Dict[str, Any] = field(default_factory=dict)
    sse_metrics: Dict[str, Any] = field(default_factory=dict)
