#!/usr/bin/env python3
import sys
import os

def read_file_or_default(path, default="No log available."):
    if os.path.exists(path):
        try:
            with open(path, "r", encoding="utf-8") as f:
                content = f.read().strip()
                return content if content else default
        except Exception as e:
            return f"Error reading {os.path.basename(path)}: {e}"
    return default

def get_tail(content, lines=15):
    lines_list = content.splitlines()
    if len(lines_list) <= lines:
        return content
    return "\n".join(lines_list[-lines:])

def generate_pr_body(issue_num, run_dir):
    scope_check_path = os.path.join(run_dir, "scope_check.txt")
    targeted_tests_path = os.path.join(run_dir, "targeted_tests.log")
    full_tests_path = os.path.join(run_dir, "full_tests.log")
    
    scope_content = read_file_or_default(scope_check_path)
    targeted_content = get_tail(read_file_or_default(targeted_tests_path))
    full_content = get_tail(read_file_or_default(full_tests_path))
    
    pr_body = f"""# Automation PR: Issue #{issue_num}

Closes #{issue_num}

## Validation Evidence

### Scope Check
```
{scope_content}
```

### Targeted Tests
```
{targeted_content}
```

### Full Test Suite
```
{full_content}
```

---
*PR automatically generated by Content-Creation Automation Runner.*
"""
    return pr_body

def main():
    if len(sys.argv) < 3:
        print("Usage: issue_pr_body.py <issue_number> <run_dir>", file=sys.stderr)
        sys.exit(2)
        
    issue_num = sys.argv[1]
    run_dir = sys.argv[2]
    
    pr_body = generate_pr_body(issue_num, run_dir)
    print(pr_body)

if __name__ == "__main__":
    main()
